import { Outfit } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/session-wrapper";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "energized",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
      <html lang="en">
        <body
          className={`${outfit.variable} antialiased`}
        >
          <SessionWrapper>
            {children}
          </SessionWrapper>
        </body>
      </html>
  );
}