import { Outfit } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/session-wrapper";
import { ThemeProvider } from "@/context/theme-context";
import {RouteChangeListener} from "@/handlers/route-change-listener";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "energized",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
      <html lang="en">
        <body
          className={`${outfit.variable} antialiased`}
        >
          <RouteChangeListener />
          <ThemeProvider>
            <SessionWrapper>
              {children}
            </SessionWrapper>
          </ThemeProvider>
        </body>
      </html>
  );
}